Story6/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('tweetpage.urls')),
]

tweetpage/urls.py
from django.urls import path
from django.conf.urls import url
from . import views

app_name = 'tweetpage'

urlpatterns = [
    path('', views.tweet, name='tweet'),
    path('profil/', views.profil, name='profil'),
    path('search/', views.search, name='search'),
    path('tutorial/', views.tutorial, name='tutorial'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    url(r'tweet/(?P<pk>[0-9]+)/delete/$',
        views.tweetDelete.as_view(), name='tweetDelete')
]

tweetpage/models.py
from django.db import models


class savedTweet(models.Model):
    tweet = models.CharField(max_length=100)
    date = models.DateTimeField(auto_now_add=True)

tweetpage/forms.py
from django import forms
from tweetpage import models


class tweetForm(forms.Form):
    tweet = forms.CharField(
        label='Tweeting... ',
        required=True,
        widget=forms.Textarea(attrs={
            'class': 'form-control',
            'type': 'text',
            'placeholder': "Let's tweet here!"})
    )


class Meta:
    model = models.savedTweet
    fields = ('tweet')

tweetpage/views.py
from django.shortcuts import render, redirect
from django.views.generic.edit import DeleteView
from django.urls import reverse_lazy
from .models import savedTweet
from .forms import tweetForm

from django.http import (
    HttpResponseNotAllowed, HttpResponseRedirect,
    HttpResponseForbidden, HttpResponseNotFound,
)
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, authenticate, logout


class tweetDelete(DeleteView):
    model = savedTweet
    success_url = reverse_lazy('tweetpage:tweet')


def tweet(request):
    if request.method == 'POST':
        form = tweetForm(request.POST)

        if 'id' in request.POST:
            savedTweet.objects.get(id=request.POST['id']).delete()
            return redirect('/')

        if form.is_valid():
            # tweet = request.POST['tweet']
            tweet = savedTweet(
                tweet=form.data['tweet']
            )
            tweet.save()
            return redirect('/')

    else:
        form = tweetForm()

    tweet_content = {'events': savedTweet.objects.all().values(),
                     'form': form}
    return render(request, 'tweet.html', tweet_content)


def profil(request):
    return render(request, 'profil.html')


def search(request):
    return render(request, 'search.html')


def tutorial(request):
    return render(request, 'nginx.html')


def login_view(request):
    if request.user.is_authenticated:
        return HttpResponseRedirect('/')

    if request.method == 'GET':
        form = AuthenticationForm()
        login_content = {'form': form}
        return render(request, 'login.html', login_content)

    if request.method == 'POST':
        form = AuthenticationForm(request=request, data=request.POST)

        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)

            if user is not None:
                login(request, user)
                return HttpResponseRedirect('/')

        else:
            # kalo error
            login_content = {'form': form}
            return render(request, 'login.html', login_content)


def logout_view(request):
    logout(request)
    return HttpResponseRedirect('/')

tweetpage/templates/login.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <title>Sign Me!</title>
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-light" id="nav">
        <a class="navbar-brand" href="{% url 'tweetpage:tweet' %}" style="color: gray;">PS</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" style="padding-left: 30px;" href="{% url 'tweetpage:profil' %}">Profil</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" style="padding-left: 30px;" href="{% url 'tweetpage:search' %}">Cari Buku</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" style="padding-left: 30px;" href="{% url 'tweetpage:tutorial' %}">Tutorial</a>
                </li>
                <li class="nav-item dropdown" id="dropdown">
                    <a style="padding-left: 30px;" class="nav-link dropdown-toggle" id="navbarDropdown" role="button"
                        data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Ubah Tema</a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="" id="winter-blue">Winter Blue</a>
                        <a class="dropdown-item" href="" id="autumn-red">Autumn Red</a>
                    </div>
                </li>
            </ul>
        </div>
    </nav>

    <section class="jumbotron half container-fluid flex-column flex-lg-row m-auto w-50" id="bg-up">
        <h2 style="display: flex; justify-content: center;">Login</h2>
    </section>

    <section class="schedule w-100 d-flex flex-column flex-lg-row justify-content-center align-items-center"
        id="body-dark">
        <div class="half container-fluid flex-column flex-lg-row m-auto w-50" style="padding-bottom: 2em;" id="bg-down">
            <div style="display: flex; justify-content: center;">
                {% if form.errors %}
                {% for field in form %}
                {% for error in field.errors %}
                <div class="alert alert-danger">
                    <strong>{{ error|escape }}</strong>
                </div>
                {% endfor %}
                {% endfor %}
                {% endif %}

                {% if form.non_field_errors %}
                {% for error in form.non_field_errors %}
                <div class="alert alert-danger">
                    <strong>{{ error|escape }}</strong>
                </div>
                {% endfor %}
                {% endif %}

                <form method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <div style="padding-left: 120px;">
                        <button class="btn btn-dark" type="submit">Login</button>
                    </div>
                </form>
            </div>
        </div>
    </section>

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
    <script type="text/javascript" src="../static/query.js"></script>
</body>

</html>

tweetpage/templates/profil.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <title>Read Me!</title>
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-light" id="nav">
        <a class="navbar-brand" href="{% url 'tweetpage:tweet' %}" style="color: gray;">PS</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" style="padding-left: 30px;" href="{% url 'tweetpage:profil' %}">Profil<span
                            class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" style="padding-left: 30px;" href="{% url 'tweetpage:search' %}">Cari Buku</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" style="padding-left: 30px;" href="{% url 'tweetpage:tutorial' %}">Tutorial</a>
                </li>
                <li class="nav-item dropdown" id="dropdown">
                    <a style="padding-left: 30px;" class="nav-link dropdown-toggle" id="navbarDropdown" role="button"
                        data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Ubah Tema</a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="" id="winter-blue">Winter Blue</a>
                        <a class="dropdown-item" href="" id="autumn-red">Autumn Red</a>
                    </div>
                </li>
            </ul>
            {% if user.is_authenticated %}
            <a class="nav-link" href="{% url 'tweetpage:logout' %}" style=" color: rgb(80, 80, 80);"><b>LOGOUT</b></a>
            {% else %}
            <a class="nav-link" href="{% url 'tweetpage:login' %}" style="color: rgb(80, 80, 80);"><b>LOGIN</b></a>
            {% endif %}
        </div>
    </nav>

    <section class="half container-fluid flex-column flex-lg-row m-auto w-50" id="bg-up">
        <br>
        <div style="text-align: center;">
            <h2>Profil</h2>
        </div>
        <br>
        <div class="text-center">
            <img src="../static/Putsal.jpeg" class="rounded" style="width: 15rem; height: 10rem;" alt="Foto Profil">
            <br>
            <br>
            <p>Nama: Putri Salsabila</p>
            <p>NPM: 1806186805</p>
        </div>
        <br>
    </section>

    <section class="schedule w-100 d-flex flex-column flex-lg-row justify-content-center align-items-center"
        id="body-dark">
        <div class="half container-fluid flex-column flex-lg-row m-auto w-50" style="padding-bottom: 2em;" id="bg-down">
            <button class="accordion">Aktivitas</button>
            <div class="panel">
                <p>Saya sangat suka mendesain dan bermain games. Ditambah saya berkuliah
                    di Fasilkom UI, saya jadi semakin tau tentang <b>UI/UX Designer</b>. Aktivitas lainnya yaitu
                    saya berenang tiap 3 minggu 1x dan saya juga langganan nonton bioskop 1 bulan
                    sekali bersama keluarga.</p>
            </div>
            <button class="accordion">Organisasi dan Kepanitiaan</button>
            <div class="panel">
                <p>Saya pernah menjadi anggota OSIS dan anggota Komisi Keagamaan MPK di SMAN 2 Depok. Saat ini, saya
                    sedang mengikuti 2 kepanitiaan di Fasilkom UI, yaitu sebagai anggota divisi dokumentasi PMB 2019
                    dan sebagai VPJ MKD Pemira Fasilkom 2019.</p>
            </div>
            <button class="accordion">Prestasi</button>
            <div class="panel">
                <p>Saya tidak memiliki banyak prestasi akademik maupun non-akademik. Saya pernah menjuarai lomba
                    mewarnai dan lomba <i>cat walk modelling</i> saat SD. Saya juga menjuarai lomba <i>Thinking
                        Skill Teen</i> juara 2 di saat SMP.</p>
            </div>
        </div>
        <br>
    </section>

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous">
        </script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous">
        </script>
    <script type="text/javascript" src="{% static 'query.js' %}"></script>
</body>

</html>

tweetpage/templates/search.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <title>Search Me!</title>
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-light" id="nav">
        <a class="navbar-brand" href="{% url 'tweetpage:tweet' %}" style="color: gray;">PS</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" style="padding-left: 30px;" href="{% url 'tweetpage:profil' %}">Profil</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" style="padding-left: 30px;" href="{% url 'tweetpage:search' %}">Cari Buku<span
                            class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" style="padding-left: 30px;" href="{% url 'tweetpage:tutorial' %}">Tutorial</a>
                </li>
                <li class="nav-item dropdown" id="dropdown">
                    <a style="padding-left: 30px;" class="nav-link dropdown-toggle" id="navbarDropdown" role="button"
                        data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Ubah Tema</a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="" id="winter-blue">Winter Blue</a>
                        <a class="dropdown-item" href="" id="autumn-red">Autumn Red</a>
                    </div>
                </li>
            </ul>
            {% if user.is_authenticated %}
            <a class="nav-link" href="{% url 'tweetpage:logout' %}" style=" color: rgb(80, 80, 80);"><b>LOGOUT</b></a>
            {% else %}
            <a class="nav-link" href="{% url 'tweetpage:login' %}" style="color: rgb(80, 80, 80);"><b>LOGIN</b></a>
            {% endif %}
        </div>
    </nav>

    <section class="half container-fluid flex-column flex-lg-row m-auto w-50" id="bg-up">
        <br>
        <h2 style="text-align: center">{{ user.username }} Mau Cari Buku Apa?</h2>
        <br>
        <div class="col">
            <label for="search">Cari Buku</label>
            <input type="text" class="form-control" id="searchbook" placeholder="Cari...">
            <br>
        </div>
    </section>

    <section class="schedule w-100 d-flex flex-column flex-lg-row justify-content-center align-items-center"
        id="body-dark">
        <div class="half container-fluid flex-column flex-lg-row m-auto w-50" style="padding-bottom: 2em;" id="bg-down">
            <div class="col">
                <table class="table table-hover bg-light" id="book-table"></table>
            </div>
        </div>
    </section>

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous">
        </script>
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous">
        </script>
    <script type="text/javascript" src="{% static 'query.js' %}"></script>
    <script type="text/javascript" src="{% static 'search.js' %}"></script>
</body>

</html>

tweetpage/templates/tweet.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <title>Tweet Me!</title>
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-light" id="nav">
        <a class="navbar-brand" href="{% url 'tweetpage:tweet' %}">PS</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" style="padding-left: 30px;" href="{% url 'tweetpage:profil' %}">Profil</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" style="padding-left: 30px;" href="{% url 'tweetpage:search' %}">Cari Buku</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" style="padding-left: 30px;" href="{% url 'tweetpage:tutorial' %}">Tutorial</a>
                </li>
                <li class="nav-item dropdown" id="dropdown">
                    <a style="padding-left: 30px;" class="nav-link dropdown-toggle" id="navbarDropdown" role="button"
                        data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Ubah Tema</a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="" id="winter-blue">Winter Blue</a>
                        <a class="dropdown-item" href="" id="autumn-red">Autumn Red</a>
                    </div>
                </li>
            </ul>
            {% if user.is_authenticated %}
            <a class="nav-link" href="{% url 'tweetpage:logout' %}" style=" color: rgb(80, 80, 80);"><b>LOGOUT</b></a>
            {% else %}
            <a class="nav-link" href="{% url 'tweetpage:login' %}" style="color: rgb(80, 80, 80);"><b>LOGIN</b></a>
            {% endif %}
        </div>
    </nav>

    <section class="half container-fluid flex-column flex-lg-row m-auto w-50" id="bg-up">
        <br>
        <h2 style="text-align: center">Halo {{ user.username }}, Apa Kabar?</h2>
        <br>
        <div class="schedule col-sm h-100 d-flex justify-content-center align-items-center">
            <form method="POST">
                {% csrf_token %}
                {% for field in form %}
                <p class="w-100 justify-content-center my-1">{{ field.label }} <br> {{ field }}</p>
                {% endfor %}
                <button id="submit" type="submit" value="Submit" class="btn btn-dark mx-auto mt-2"
                    style="float: right;">Submit</button>
            </form>
        </div>
        <br>
    </section>

    <section class="schedule w-100 d-flex flex-column flex-lg-row justify-content-center align-items-center"
        id="body-dark">
        <div class="row m-auto w-50" style="overflow: hidden; overflow-y:auto; height: 70%;" id="bg-down">
            {% for i in events %}
            <div>
                <h5 style="padding-left: 15px">Your Tweet :</h5>
            </div>
            <div class="container">
                <div class="text-monospace">
                    <p>{{ i.tweet }}</p>
                    <p style="float: right;">{{ i.date }}</p>
                </div>
            </div>

            <div class="col-sm-12 d-flex align-items-end justify-content-end" style="padding-right: 35px">
                <form method="POST" action="{% url 'tweetpage:tweetDelete' i.id %}">
                    {% csrf_token %}
                    <input name="id" value="{{i.id}}" type="hidden">
                    <button id="delete" type="" class="btn btn-outline-dark btn-sm"
                        style="margin-left: 30%; font-size: 0.8rem;">Delete</button>
                </form>
            </div>
            {% endfor %}
        </div>
    </section>

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
    <script type="text/javascript" src="../static/query.js"></script>
</body>

</html>